# Generated by Django 2.1 on 2019-07-26 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nijaherbs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('name',), 'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
        migrations.RenameField(
            model_name='herb',
            old_name='botanicalName',
            new_name='botanical_Name',
        ),
        migrations.RenameField(
            model_name='herb',
            old_name='englishName',
            new_name='english_Name',
        ),
        migrations.RenameField(
            model_name='herb',
            old_name='localName',
            new_name='local_Name',
        ),
        migrations.AddField(
            model_name='herb',
            name='description',
            field=models.TextField(help_text='Enter description of the herb', null=True),
        ),
    ]
