# Generated by Django 2.1 on 2019-07-26 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nijaherbs', '0002_auto_20190726_2129'),
    ]

    operations = [
        migrations.AddField(
            model_name='herb',
            name='health_benefits',
            field=models.TextField(help_text='Enter the health benefits of the of the herb', null=True),
        ),
        migrations.AddField(
            model_name='herb',
            name='uses',
            field=models.TextField(help_text='Enter uses of the herb', null=True),
        ),
    ]
