# Generated by Django 2.1 on 2019-07-28 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nijaherbs', '0003_auto_20190726_2350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='herb',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
