# Generated by Django 2.1 on 2019-07-28 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nijaherbs', '0004_auto_20190728_0618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='herb',
            name='image',
            field=models.ImageField(blank=True, upload_to='herb-images/'),
        ),
    ]
