# Generated by Django 2.1 on 2019-07-29 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nijaherbs', '0006_auto_20190728_1558'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='herb',
            options={'ordering': ('-id',)},
        ),
    ]
