# Generated by Django 2.1 on 2019-07-29 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nijaherbs', '0007_auto_20190729_1154'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='herb',
            options={'ordering': ('-created_on',)},
        ),
        migrations.AddField(
            model_name='herb',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
